---
- name: Deploy MERN Stack Application
  hosts: your_host_ip
  remote_user: your_ssh_username
  become: yes
  vars:
    backend_port: 5000
    frontend_port: 3000

  tasks:
    - name: Install Docker dependencies
      apt:
        name: "{{ item }}"
        state: present
      loop:
        - apt-transport-https
        - ca-certificates
        - curl
        - software-properties-common

    - name: Add Docker APT GPG key
      apt_key:
        url: https://download.docker.com/linux/ubuntu/gpg
        state: present

    - name: Add Docker repository
      apt_repository:
        repo: deb [arch=amd64] https://download.docker.com/linux/ubuntu {{ ansible_distribution_release }} stable
        state: present

    - name: Update apt and install Docker
      apt:
        update_cache: yes
        name: docker-ce
        state: latest

    - name: Install Docker Compose
      get_url:
        url: https://github.com/docker/compose/releases/download/1.29.2/docker-compose-Linux-x86_64
        dest: /usr/local/bin/docker-compose
        mode: 'a+x'

    - name: Start and enable Docker service
      service:
        name: docker
        state: started
        enabled: yes

    - name: Clone your MERN stack repository
      git:
        repo: https://github.com/Vinodkumarseetha/Mernstack
        dest: /home/{{ remote_user }}/mern-docker-app

    - name: Build and start Docker containers
      command: docker-compose -f /home/{{ remote_user }}/mern-docker-app/docker-compose.yml up -d
